import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/components/shared/Navbar'
import Sidebar from '@/components/shared/Sidebar'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function Layout ({
    children,
  }: {
    children: React.ReactNode
  }
  ){
    return(
        <html lang="en">
          <div className='flex h-screen flex-col md:flex-row md:overflow-hidden bg-slate-900'>
              <div className="w-full flex-none md:w-64 bg-slate-800 ">
                  <Sidebar />
              </div>
              <div className="flex-grow p-6 md:overflow-y-auto md:p-12">
                  <Navbar/>
                  {children}
              </div>
          </div>
      </html>
    )
  }

